name: Svelte CI

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Deploy repo to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
    
    - name: Kill running node processes & Start game coordinator 
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: '${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}'
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
        debug: false
        command: |
          pkill -f node
          npm install
          npm run build
          nohup npm run prod < /dev/null &> /dev/null &
